language: python

python:
  - "3.6"

install:
  # Tests if cargo works
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - cargo --version 
  - pip install -r requirements.txt
  - pip install .

script: python setup.py test
